controllers/post.js
middleware/auth.js
routes/post.js

1. Add patchPost swagger
(1) add authorization
(2) input postId
(3) if the title or content is null
(3) If authorization user is not the author of the post
2. Add createPost swagger
(1) input resourceId
(2) if resourceId is empty

Tjm 59 add patchpost and createmoviepost swagger

---

controllers/user.js

change req.params to req: change to get userId through middleware auth.

TJM54 fix: change patch user id

---

controllers/user.js

TJM60 patch user swagger

---

controllers/comment.js
controllers/post.js
controllers/user.js
routes/comment.js

TJM 82 get Comment with postId in query

---

controllers/post.js
routes/post.js
utils/swagger.yaml

Tjm 87 like concerned post swagger

---

controllers/movie.js
routes/movie.js
utils/swagger.yaml

add listmoviebytag, searchmoviebyname and getmoviebyId swagger

add movie Swagger

---

api/axios.js
controllers/movie.js
routes/movie.js
utils/formatMovieData.js
utils/swagger.yaml

Tjm 95 get comment by id swagger but fixed

---

api/axios.js
controllers/movie.js
routes/movie.js
utils/formatMovieData.js
utils/swagger.yaml

Tjm 98 get movies by top rated

---

utils/formatMovieData.js

Delete popularity property in the getmoviedetails controller

delete popularity property

---

.eslintrc.json
models/Comment.js

change eslint rule to allow anonymouse function, used in schemas for virtuals and hash.

fix: eslint rule and model

---

api/axios.js
controllers/movie.js
routes/movie.js
utils/swagger.yaml

1. add getmoviesbycondition api
2. add page property into listmoviebytag api

Tjm 107 get movies by genre

---

controllers/user.js
middleware/auth.js
models/Post.js

feat: token return user login

---

controllers/user.js

fix: wrap loginmsg

---

api/axios.js
controllers/movie.js

Tjm 113 modify get videos api

---

middleware/auth.js

fix: auth token

---

api/axios.js
controllers/movie.js

modify api: when sending a request to getTopRatedMovies controller, it will only response movie details without youtube links.
The front-end will do the second fetch to getMovidTrailerbyId to get the youtube links then.

Modify api for fetching youtube link

---

api/axios.js
controllers/post.js
middleware/auth.js
models/Post.js
models/User.js
utils/formatDiscussionData.js
utils/swagger.yaml

Tjm 124 return discussion data divided by pages

---

api/axios.js
controllers/user.js
routes/user.js
utils/swagger.yaml

feat: user profile

---

controllers/comment.js
package-lock.json

feat: add sortBy Date and topLikes

---

controllers/comment.js
controllers/post.js

feat: make comments into nested format

---

controllers/user.js
routes/user.js

add verify token method
1. valid
2. token is null
3. invalid token

feat: add verify token method

---

controllers/post.js

create movie post after determine if resourceid  already exist in some post

fix: create movie post after determine resourceid is not exist

---

controllers/movie.js
controllers/post.js
routes/movie.js

replay resourceId with movie postId

Tjm 160 fix getmoviedetail api from resource id to post

---

controllers/post.js
middleware/auth.js
package-lock.json
routes/post.js
utils/formatDiscussionData.js
utils/swagger.yaml

create endpoints for title and content search for posts.

Tjm 146 create endpoints for title and content search

---

controllers/user.js

fix: warp user profile

---

controllers/comment.js

fix: comment length

---

app.js
controllers/comment.js
controllers/notification.js
controllers/post.js
package-lock.json
package.json
routes/notification.js
routes/post.js
services/createNotification.js
utils/swagger.yaml

1. change likepost and unlikepost into one toggleLikePost method
2. add createNotification in toggleLikePost
3. add toggleFollowPost method

Tjm 167 socket io

---

controllers/notification.js
controllers/user.js
models/User.js

hash password after update password

fix: reset password hash

---

controllers/notification.js
models/Comment.js

add comment content output to notification api

fix: add comment content to notification api

---

app.js
controllers/notification.js
models/Comment.js

add production url in .env file

Fix production url

---

controllers/hashtag.js
controllers/post.js
models/Hashtag.js
models/Post.js
routes/hashtag.js
routes/index.js

feat: create hashtag controller

---

constants/constants.js

fix: replace sorry image to imdb image

fix: replace sorry image

---

utils/convertHtmlEntities.js

fix: covert html tag

---

utils/formatMovieData.js

是0的 vote average 改成了 --
movie card 里面显示的 genre 数量改成了 2 个

change zero vote average to hyphen

---

controllers/hashtag.js
package-lock.json
routes/hashtag.js
utils/formatDiscussionData.js

feat: add getPostByHashTagId
